name: Run Automated Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (if using PyTest)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the test cases
      - name: Run tests
        run: pytest 
